website/views.py
from flask import Blueprint, render_template, redirect, url_for,request,flash
from .models import Movie,Venue,User,Admin,Booking
from . import db
from flask_login import login_required,current_user,login_manager
from sqlalchemy import func
import matplotlib
import numpy as np
matplotlib.use('Agg')    #used to covert it as non-GUI fast rendering
import matplotlib.pyplot as plt
import operator

views = Blueprint('views', __name__)


@views.route('/login_failed')
@login_required
def login_failed():
    return redirect(url_for('auth.login_get_user'))


@views.route('/signup_failed')
@login_required
def signup_failed():
    return redirect(url_for('auth.signup_get_admin'))

@views.route('/city_user')
@login_required
def city_user():
    return render_template("usercity.html",user=current_user)

@views.route('/city_admin')
@login_required
def city_admin():
    return render_template("admincity.html",admin=current_user)

@views.route('/city_user1',methods=['GET','POST'])
@login_required
def city_user1():
    if request.method == 'POST':
        user1 = User.query.filter_by(user_name = current_user.user_name).first()
        user1.user_city = request.form.get("city")
        db.session.commit()
    return redirect(url_for('views.user11'))

@views.route('/city_admin1',methods=['GET','POST'])
@login_required
def city_admin1():
    if request.method == 'POST':
        admin1 = Admin.query.filter_by(admin_name = current_user.admin_name).first()
        admin1.admin_city = request.form.get("city")
        db.session.commit()
    return redirect(url_for('views.add_movies')) 


@views.route('/sign_up_success')
@login_required
def sign_up_success():
    return redirect(url_for('auth.login_get_user'))

@views.route('/sign_up_failed')
@login_required
def sign_up_failed():
    return redirect(url_for('auth.signup_admin'))
 

@views.route('/add_movies',methods=['GET','POST'])
@login_required
def add_movies():
    try:
        if request.method == 'POST':
            movie_n = request.form.get("moviename")
            movie_m_c = request.form.get("moviecapacity")
            movie_t_c = request.form.get("ticketcost")
            movie_s = request.form.get("showtime")
            movie_l = request.form.get("length")
            movie_v = request.form.get("venue")
            venue = Venue.query.all()
            movie = Movie.query.all()
            for i in movie:
                if(str(i.movie_name) == str(movie_n) and int(i.movie_capacity) == int(movie_m_c) and str(i.movie_show_time) == str(movie_s) and str(i.movie_venue) == str(movie_v)):
                    flash("Movie already Exists !!!")
                    return render_template("Addmovies.html",admin=current_user)
                
            for row in venue:
                if(row.venue_name == movie_v):
                    new_movie = Movie(movie_name = movie_n, movie_capacity = movie_m_c, movie_ticket_cost = movie_t_c , movie_show_time = movie_s, movie_length = movie_l, movie_venue = movie_v )
                    db.session.add(new_movie)
                    db.session.commit()
                    flash("Movie added Successfully !!!")
                    return redirect(url_for('views.add_movies')) 
                
            flash("Entered venue doesn't exists, create it first !!!")
            return redirect(url_for('views.add_venue'))   
        return render_template("Addmovies.html",admin=current_user)
    except:
        return "<h2>Something went wrong.</h2>"


@views.route('/add_venue',methods=['GET','POST'])
@login_required
def add_venue():
    try:
        if request.method == 'POST':
            Venue_n = request.form.get("Venuename")
            Venue_c = request.form.get("Capacity")
            Venue_l = request.form.get("venuelocation")
            Venue_p = request.form.get("venueplace")
            Venue_r = request.form.get("Rating")
            new_venue = Venue( venue_name = Venue_n, venue_capacity = Venue_c,venue_rating = Venue_r,venue_location = Venue_l,venue_city = Venue_p )
            db.session.add(new_venue)
            db.session.commit()
            flash("Venue added Successfully !!!")
            return redirect(url_for('views.add_venue'))
    except:
        flash("Venue already exists !!!")
        return redirect(url_for('views.add_venue'))
    return render_template("AddVenue.html",admin=current_user)


@views.route('/view_movies',methods=['GET','POST'])
@login_required
def view_movies():
    movie=Movie.query.all()
    return render_template("viewmovies.html", movie=movie,admin=current_user)

@views.route('/view_venue',methods=['GET','POST'])
@login_required
def view_venue():
    venue=Venue.query.all()
    return render_template("viewvenue.html",venue=venue,admin=current_user)

@views.route('/remove_movie/<int:id>')
@login_required
def remove_movie(id):
    movie_remove = Movie.query.get(id)
    db.session.delete(movie_remove)
    db.session.commit()
    return redirect(url_for("views.view_movies"))

@views.route('/remove_venue/<int:id>')
@login_required
def remove_venue(id):
    venue_remove = Venue.query.get(id)
    id1=id
    venuename = venue_remove.venue_name
    print(venuename)
    movie = Movie.query.all()
    list_m = []

    for rows in movie:
        if(rows.movie_venue == venuename):
            list_m.append(rows)

    if list_m != []:
        for i in list_m:
            db.session.delete(i)
            db.session.commit()
        return redirect(url_for("views.delete_venue_row",id=id1))
    
    if list_m == []:
        venue_remove = Venue.query.get(id)
        db.session.delete(venue_remove)
        db.session.commit()
        return redirect(url_for("views.view_venue")) 


@views.route('/delete_venue_row/<int:id>')
@login_required
def delete_venue_row(id):
    venue_remove = Venue.query.get(id)
    db.session.delete(venue_remove)
    db.session.commit()
    return redirect(url_for("views.view_venue"))


@views.route('/update_movie/<int:id>',methods=['GET','POST'])
@login_required
def update_movie(id):
    movie_update = Movie.query.get(id)
    movie = Movie.query.all()
    if request.method == 'POST':  
        venue = Venue.query.all()
        movie_v = request.form.get("venue") 
        movie_n = request.form.get("moviename")
        movie_m_c = request.form.get("moviecapacity")
        movie_s = request.form.get("showtime")
        movie_t_c = request.form.get("ticketcost")
        movie_l = request.form.get("length")
    for i in movie:
        if(str(i.movie_name) == str(movie_n) and int(i.movie_capacity) == int(movie_m_c) and str(i.movie_show_time) == str(movie_s) and str(i.movie_venue) == str(movie_v) and str(i.movie_length) == str(movie_l) and int(i.movie_ticket_cost) == int(movie_t_c)):
            flash("Movie already Exists !!!")
            return redirect(url_for("views.view_movies"))
        
    # update form venue should exists in venue table
    for row in venue:
        if(row.venue_name == movie_v):
            movie_update.movie_name = request.form.get("moviename")
            movie_update.movie_capacity = request.form.get("moviecapacity")
            movie_update.movie_ticket_cost = request.form.get("ticketcost")
            movie_update.movie_show_time = request.form.get("showtime")
            movie_update.movie_length = request.form.get("length")
            movie_update.movie_venue = request.form.get("venue")
            db.session.commit()
            flash("Details updated successfully !!!")
            return redirect(url_for("views.view_movies")) 
            
    flash("Entered venue doesn't exists, create it first !!!")
    return redirect(url_for('views.add_venue'))

@views.route('/update_venue/<int:id>',methods=['GET','POST'])
@login_required
def update_venue(id):
    venue_update = Venue.query.get(id)
    if request.method == 'POST':
        venue_update.venue_name = request.form.get("venuename")
        venue_update.venue_capacity = request.form.get("venuecapacity")
        venue_update.venue_location = request.form.get("venuelocation")
        venue_update.venue_city = request.form.get("venueplace")
        venue_update.venue_rating = request.form.get("venuerating")
        db.session.commit()
        flash("Details updated successfully !!!")
        return redirect(url_for("views.view_venue")) 


@views.route('/user11', methods=['GET', 'POST'])
@login_required
def user11():
    movie = Movie.query.group_by(Movie.movie_name)
    u_city = current_user.user_city
    venue = Venue.query.all()
    v_list = []
    for i in venue:
        if i.venue_city.lower() == u_city.lower():
            v_list.append(i.venue_name)
    m_list = []        
    for i in movie:
        for j in v_list:
            if i.movie_venue == j:
                m_list.append(i)                   
    return render_template("user1.html", m1 = m_list,user=current_user) 

@views.route('/all_movies', methods=['GET', 'POST'])
@login_required
def all_movies():
    movie = Movie.query.group_by(Movie.movie_name)
    m_list = []
    for i in movie:
        m_list.append(i)
    return render_template("allmovies.html", m1 = m_list,user=current_user)

@views.route('/user22/<string:name>', methods=['GET', 'POST'])
@login_required
def user22(name):
    try:
        m1 = name
        movie = Movie.query.filter(Movie.movie_name == name).all()
        d={}
        for rows in movie:
            venue=rows.movie_venue
            venue1 = Venue.query.filter(Venue.venue_name == venue).all()
            for i in venue1:
                venuerating =i.venue_rating
                venuelocation =i.venue_location
                venueplace =i.venue_city
                d[rows.movie_id] = [rows.movie_venue,rows.movie_capacity,venuerating,venuelocation,venueplace]
        return render_template("user2.html",movie_name =m1, m3 = d ,user=current_user)
    except:
        return "<h2>Something went wrong.</h2>"

@views.route('/booking33/<int:id>', methods=['GET', 'POST'])
@login_required
def booking33(id):
    try:

website/templates/AddVenue.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>add venue</title>
    <link rel="stylesheet" type="text/css" href="../static/Addvenue.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>
<body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

    {% for message in get_flashed_messages() %}
    <div class="alret" style="position: relative;">
      <div class="alert alert-warning alert-dismissible fade show" role="alert" align="center" style=" margin-top: 40px; color: white;background-image: linear-gradient(50deg,#cc2b5e,#753a88); width: 1400px; margin-left: 60px; top: 20px; height: 40px; padding-top: -5px; position: absolute;">
          <div style="font-size: medium; margin-top: -8px; font-family: Rockwell;"><b>{{message}}</b></div> 
          <button type="button" style="background-color: aliceblue; height: 0px;" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>  
    </div>      
    {% endfor %}

    <nav class="navbar navbar-dark fixed-top" style="opacity: .985; background-color: black;box-shadow: rgb(38, 57, 77) 0px 20px 30px -10px;">
      <div class="container-fluid">  
        <a class="navbar-brand" href="#" style="margin-left: 30px; font-family:Copperplate Gothic Light ; font-size: 120%;"><span style="font-size: 110%;">🎭</span> <b>Ticket Show</b><span style="margin-left: 780px;"><b>Welcome &nbsp&nbsp{{admin.admin_name}}</b></span><span style="margin-left: 50px;"><b>{{admin.admin_city}}</b></span><span><a href="/logout" style="color: aliceblue; text-decoration: none; cursor: pointer; margin-left: 30px;"><b>Logout</b></a></span></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="offcanvas offcanvas-end text" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel " style="background-color: black;">
          <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel" style="color: white; font-family: Copperplate Gothic Light ;"><span style="font-size: 110%;">🎭</span> <b>Ticket Show</b></h5>
            <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
          </div>
          <div class="offcanvas-body">
            <ul class="navbar-nav justify-content-end flex-grow-1 pe-3" style="font-family: MS PMincho; font-size: 120%;">
              <li class="nav-item">
                <a class="nav-link" href="/add_movies"><b>🍿&nbsp&nbsp&nbsp&nbspAdd Movie</b></a>
              </li>
              <br>
              <li class="nav-item">
                  <a class="nav-link" href="/add_venue"><b>🍿&nbsp&nbsp&nbsp&nbspAdd Theater/Venue</b></a>
              </li>
              <br>
              <li class="nav-item">
                  <a class="nav-link" href="/view_movies"><b>🍿&nbsp&nbsp&nbsp&nbspView Movie</b></a>
              </li>
              <br>
              <li class="nav-item">
                  <a class="nav-link" href="/view_venue"><b>🍿&nbsp&nbsp&nbsp&nbspView Theater/Venue</b></a>
              </li>
              <br>
              <li class="nav-item">
                <a class="nav-link " aria-current="page" href="/city_admin"><b>🍿&nbsp&nbsp&nbsp&nbsp Change City</b></a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </nav> 
    
    <div class="container">
        <br>
        <br>
        <div class="login-center" style="font-family: sans-serif; height: 510px; width: 485px; background-color: rgba(240,248,255,.75); border-radius: 50px; margin-left: 680px; margin-top: 70px; box-shadow: rgba(0, 0, 0, 0.56) 0px 22px 70px 4px;" align="center">
            <form class="login-form" action="" method="POST">   
                <div class="login-mid">
                    <br>
                    <br>
                    <div class="login-form-item" style="margin-left:50px; font-size: 17px; display: flex; flex: 6; gap:20px; font-family: cursive; margin-top: 5px;">
                        <label for="Venuename">Venue Name</label>
                        <input  required type="text" name="Venuename" id="Venuename" style="width: 240px; ">
                    </div>
                    <br>
                    <br>
                    <div class="login-form-item" style="margin-left:30px; font-size: 17px; display: flex; flex: 6; gap:20px; font-family: cursive;">
                      <label for="venuelocation">Venue Location</label>
                      <input required type="text" name="venuelocation" id="venuelocation" style="width: 240px;">
                    </div>
                    <br>
                    <br>
                    <div class="login-form-item" style="margin-left:55px; font-size: 17px; display: flex; flex: 6; gap:20px; font-family: cursive;">
                      <label for="venueplace">Venue Place</label>
                      <input required  type="text" name="venueplace" id="venueplace" style="width: 240px;">
                    </div>
                    <br>
                    <br>
                    <div class="login-form-item" style="margin-left: 70px; font-size: 17px;display: flex; flex: 6; gap:30px; font-family: cursive;">
                        <label for="Capacity">Capacity</label>
                        <input type="number" name="Capacity" id="Capacity" style="width: 240px;">
                    </div>
                    <br>
                    <br>
                    <label for="Rating" style="float: left;margin-left: 75px; font-family: cursive; font-size: 17px;">Rating</label>
                    <select id="Rating" name="Rating" style=" border: 1px solid black; border-radius: 2px; width: 240px; height: 35px; float: right; margin-right: 75px;">
                        <option value="Rating"></option>
                        <option value="1 ⭐">1 ⭐ </option>
                        <option value="2 ⭐ ⭐">2 ⭐ ⭐ </option>
                        <option value="3 ⭐ ⭐ ⭐">3 ⭐ ⭐ ⭐ </option>
                        <option value="4 ⭐ ⭐ ⭐ ⭐">4 ⭐ ⭐ ⭐ ⭐ </option>
                        <option value="5 ⭐ ⭐ ⭐ ⭐ ⭐">5 ⭐ ⭐ ⭐ ⭐ ⭐ </option>
                    </select>
                    <br>
                    <br>
                    <br>
                <div class="login-footer" style="margin-left: 25px;">
                    <button type="submit" style="height: 40px; width: 100px; font-family: cursive; border-radius: 5px;">Submit</button>
                </div>   
            </form>
        </div>
    </div>  
</body>
</html>

website/templates/viewmovies.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>view movies</title>
    <link rel="stylesheet" type="text/css" href="../static/viewmovies.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>
<body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

    {% for message in get_flashed_messages() %}
    <div class="alret" style="position: relative;">
      <div class="alert alert-warning alert-dismissible fade show" role="alert" align="center" style=" margin-top: -55px; color: white;background-image: linear-gradient(50deg,#cc2b5e,#753a88); width: 1400px; margin-left: 60px; top: 20px; height: 40px; padding-top: -5px; position: absolute;">
          <div style="font-size: medium; margin-top: -8px; font-family: Rockwell;"><b>{{message}}</b></div> 
          <button type="button" style="background-color: aliceblue; height: 0px;" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>  
    </div>        
    {% endfor %}

    <nav class="navbar navbar-dark  fixed-top" style="opacity: .985; background-color: black;box-shadow: rgb(38, 57, 77) 0px 20px 30px -10px;">
      <div class="container-fluid">  
        <a class="navbar-brand" href="#" style="margin-left: 30px; font-family:Copperplate Gothic Light ; font-size: 120%;"><span style="font-size: 110%;">🎭</span> <b>Ticket Show</b><span style="margin-left: 780px;"><b>Welcome &nbsp&nbsp{{admin.admin_name}}</b></span><span style="margin-left: 50px;"><b>{{admin.admin_city}}</b></span><span><a href="/logout" style="color: aliceblue; text-decoration: none; cursor: pointer; margin-left: 30px;"><b>Logout</b></a></span></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="offcanvas offcanvas-end text" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel" style="background-color: black;">
          <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel" style="color: white; font-family: Copperplate Gothic Light ;"><span style="font-size: 110%;">🎭</span> <b>Ticket Show</b></h5>
            <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
          </div>
          <div class="offcanvas-body">
            <ul class="navbar-nav justify-content-end flex-grow-1 pe-3" style="font-family: MS PMincho; font-size: 120%;">
              <li class="nav-item">
                <a class="nav-link" href="/add_movies"><b>🍿&nbsp&nbsp&nbsp&nbspAdd Movie</b></a>
              </li>
              <br>
              <li class="nav-item">
                  <a class="nav-link" href="/add_venue"><b>🍿&nbsp&nbsp&nbsp&nbspAdd Theater/Venue</b></a>
              </li>
              <br>
              <li class="nav-item">
                  <a class="nav-link" href="/view_movies"><b>🍿&nbsp&nbsp&nbsp&nbspView Movie</b></a>
              </li>
              <br>
              <li class="nav-item">
                  <a class="nav-link" href="/view_venue"><b>🍿&nbsp&nbsp&nbsp&nbspView Theater/Venue</b></a>
              </li>
              <br>
              <li class="nav-item">
                <a class="nav-link " aria-current="page" href="/city_admin"><b>🍿&nbsp&nbsp&nbsp&nbsp Change City</b></a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </nav> 
    <div class="container">
        <div class="login-center" style="font-family: sans-serif; height: 570px; width: 720px; overflow-y: scroll; overflow-x: hidden; background-color: rgba(240,248,255,.75); border-radius: 50px; margin-left: 650px; margin-top: 100px; box-shadow: rgba(0, 0, 0, 0.56) 0px 22px 70px 4px;" align="center">
            <br>
            <div class="header" style="font-family: rockwell;">
                <h2> IN THEATER NOW 🎬...</h2>
            </div>
            <br>
            <div class="table" style="margin-left: 5px; padding-right: 30px;">
              <table>
                <tr style="font-family: Copperplate Gothic Light;">
                  <th>Name</th>
                  <th>&nbsp&nbspTicket<br>&nbsp&nbspcost</th>
                  <th>  &nbsp&nbspMovie<br>  &nbsp&nbsplength</th>
                  <th>Show<br>time</th>
                  <th>Venue</th>
                  <th>&nbsp&nbspMovie<br>&nbsp&nbsp&nbspCapacity</th>
                </tr>
                {% for i in movie %}
                <tr>
                  <td>
                    {{i.movie_name}}
                  </td>
                  <td>
                    {{i.movie_ticket_cost}}
                  </td>
                  <td>
                    {{i.movie_length}}
                  </td>
                  <td>
                    {{i.movie_show_time}}
                  </td>
                  <td>
                    {{i.movie_venue}}
                  </td>
                  <td>
                    {{i.movie_capacity}}
                  </td>
                  <td>
                    <button  formaction="/update_movie/{{i.movie_id}}"  formmethod='POST' type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal{{i.movie_id}}" style=" height: 40px; width: 100px; font-family: cursive; background-color: #cb22d7; color: white; border-color: #cb22d7;">Update</button>
                    <!-- Modal -->
                    <div class="modal fade" id="exampleModal{{i.movie_id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                      <div class="modal-dialog modal-dialog-centered">
                        <div class="modal-content">
                          <div class="modal-header" style="font-family: Bodoni MT; font-size: 18px;">
                            <p class="modal-title fs-5" id="exampleModalLabel ">UPDATE FORM</p>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                          </div>
                          <div class="modal-body">
                            <form class="login-form" action="" method= 'POST'>   
                              <div class="login-mid">
                                  <br>
                                  <div class="login-form-item" style="margin-left:50px; font-size: 18px; display: flex; flex: 6; gap:20px; font-family: cursive; margin-top: 15px;">
                                      <label for="moviename">Movie Name</label>
                                      <input type="text" name="moviename"  id="moviename" value="{{i.movie_name}}">
                                  </div>
                                  <br>
                                  <div class="login-form-item" style="margin-left: 42px; font-size: 18px;display: flex; flex: 6; gap:20px; font-family: cursive; margin-top: 15px">
                                      <label for="releasedate">Release Date</label>
                                      <input type="date" name="releasedate"  id="releasedate" value="{{i.movie_release_date}}" style="height: 35px; width: 270px;">
                                  </div>
                                  <br>
                                  <div class="login-form-item" style="margin-left:48px; display: flex; flex: 6; gap:30px;font-size: 18px; font-family: cursive;margin-top: 15px">
                                      <label for="ticketcost">Ticket Cost</label>
                                      <input type="number" name="ticketcost" id="ticketcost" value="{{i.movie_ticket_cost}}">
                                  </div>
                                  <br>
                                  <div class="login-form-item" style="margin-left:45px; display: flex; flex: 6; gap:34px;font-size: 18px; font-family: cursive;margin-top: 15px">
                                      <label for="showtime">Show Time</label>
                                      <input type="text" id="showtime" name="showtime" value="{{i.movie_show_time}}">
                                  </div>
                                  <br>
                                  <div class="login-form-item" style="margin-left:35px; display: flex; flex: 6; gap:20px;font-size: 18px; font-family: cursive;margin-top: 15px">
                                      <label for="length">Movie Length</label>
                                      <input type="text" name="length" id="length" value="{{i.movie_length}}" style="height: 32px; width: 260px;">
                                  </div>
                                  <br>
                                  <div class="login-form-item" style="margin-left:80px; display: flex; flex: 6; gap:40px;font-size: 18px; font-family: cursive;margin-top: 15px">
                                      <label for="venue">Venue</label>
                                      <input type="text" name="venue" id="venue" value="{{i.movie_venue}}">
                                  </div>
                                  <br>
                                  <div class="login-form-item" style="margin-left:30px; display: flex; flex: 6; gap:20px;font-size: 18px; font-family: cursive;margin-top: 15px">
                                    <label for="moviecapacity">Movie Capacity</label>
                                    <input type="number" name="moviecapacity" id="moviecapacity" value="{{i.movie_capacity}}" style="height: 32px; width: 260px;">
                                  </div>
                                  <br>
                              </div>
                              <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" style="background-color: black ; color: white;">Close</button>
                                <button type="submit" formaction="/update_movie/{{i.movie_id}}"  formmethod='POST'  class="btn btn-primary" style="font-family: cursive; background-color: #cb22d7; color: white; border-color: #cb22d7;">Save changes</button>
                              </div>
                            </form>                           
                          </div>
                        </div>
                      </div>
                    </div>
                  </td>
                  <td>
                    <a href="{{url_for('views.remove_movie', id = i.movie_id)}}">
                    <button type="submit" style="height: 40px; width: 100px; font-family: cursive; border-radius: 5px;">Remove</button>
                    </a>
                  </td>
                </tr>
                {% endfor %}
              </table>
            </div>
        </div>
    </div>  
</body>
</html>